export default {
  "login": "jamesoyanna",
  "id": 26815113,
  "node_id": "MDQ6VXNlcjI2ODE1MTEz",
  "avatar_url": "https://avatars.githubusercontent.com/u/26815113?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/jamesoyanna",
  "html_url": "https://github.com/jamesoyanna",
  "followers_url": "https://api.github.com/users/jamesoyanna/followers",
  "following_url": "https://api.github.com/users/jamesoyanna/following{/other_user}",
  "gists_url": "https://api.github.com/users/jamesoyanna/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/jamesoyanna/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/jamesoyanna/subscriptions",
  "organizations_url": "https://api.github.com/users/jamesoyanna/orgs",
  "repos_url": "https://api.github.com/users/jamesoyanna/repos",
  "events_url": "https://api.github.com/users/jamesoyanna/events{/privacy}",
  "received_events_url": "https://api.github.com/users/jamesoyanna/received_events",
  "type": "User",
  "site_admin": false,
  "name": "James Oyanna",
  "company": "Onesphere Solutions ",
  "blog": "https://www.jamesoyanna.com",
  "location": "Lagos, Nigeria",
  "email": null,
  "hireable": true,
  "bio": "Software Engineer-\r\nReact JS | JavaScript | Node JS | Python",
  "twitter_username": "jamesoyanna",
  "public_repos": 105,
  "public_gists": 0,
  "followers": 24,
  "following": 79,
  "created_at": "2017-03-31T10:15:35Z",
  "updated_at": "2021-05-10T12:59:43Z"
};
