export default [
  {
    login: "olahfemi",
    id: 11141249,
    node_id: "MDQ6VXNlcjExMTQxMjQ5",
    avatar_url: "https://avatars.githubusercontent.com/u/11141249?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/olahfemi",
    html_url: "https://github.com/olahfemi",
    followers_url: "https://api.github.com/users/olahfemi/followers",
    following_url:
      "https://api.github.com/users/olahfemi/following{/other_user}",
    gists_url: "https://api.github.com/users/olahfemi/gists{/gist_id}",
    starred_url: "https://api.github.com/users/olahfemi/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/olahfemi/subscriptions",
    organizations_url: "https://api.github.com/users/olahfemi/orgs",
    repos_url: "https://api.github.com/users/olahfemi/repos",
    events_url: "https://api.github.com/users/olahfemi/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/olahfemi/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "baldcodr",
    id: 5161569,
    node_id: "MDQ6VXNlcjUxNjE1Njk=",
    avatar_url: "https://avatars.githubusercontent.com/u/5161569?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/baldcodr",
    html_url: "https://github.com/baldcodr",
    followers_url: "https://api.github.com/users/baldcodr/followers",
    following_url:
      "https://api.github.com/users/baldcodr/following{/other_user}",
    gists_url: "https://api.github.com/users/baldcodr/gists{/gist_id}",
    starred_url: "https://api.github.com/users/baldcodr/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/baldcodr/subscriptions",
    organizations_url: "https://api.github.com/users/baldcodr/orgs",
    repos_url: "https://api.github.com/users/baldcodr/repos",
    events_url: "https://api.github.com/users/baldcodr/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/baldcodr/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "senthil090",
    id: 12442935,
    node_id: "MDQ6VXNlcjEyNDQyOTM1",
    avatar_url: "https://avatars.githubusercontent.com/u/12442935?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/senthil090",
    html_url: "https://github.com/senthil090",
    followers_url: "https://api.github.com/users/senthil090/followers",
    following_url:
      "https://api.github.com/users/senthil090/following{/other_user}",
    gists_url: "https://api.github.com/users/senthil090/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/senthil090/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/senthil090/subscriptions",
    organizations_url: "https://api.github.com/users/senthil090/orgs",
    repos_url: "https://api.github.com/users/senthil090/repos",
    events_url: "https://api.github.com/users/senthil090/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/senthil090/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ChinazomIfediora",
    id: 55914640,
    node_id: "MDQ6VXNlcjU1OTE0NjQw",
    avatar_url: "https://avatars.githubusercontent.com/u/55914640?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ChinazomIfediora",
    html_url: "https://github.com/ChinazomIfediora",
    followers_url: "https://api.github.com/users/ChinazomIfediora/followers",
    following_url:
      "https://api.github.com/users/ChinazomIfediora/following{/other_user}",
    gists_url: "https://api.github.com/users/ChinazomIfediora/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ChinazomIfediora/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ChinazomIfediora/subscriptions",
    organizations_url: "https://api.github.com/users/ChinazomIfediora/orgs",
    repos_url: "https://api.github.com/users/ChinazomIfediora/repos",
    events_url:
      "https://api.github.com/users/ChinazomIfediora/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ChinazomIfediora/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Onyinye91-ctrl",
    id: 54718039,
    node_id: "MDQ6VXNlcjU0NzE4MDM5",
    avatar_url: "https://avatars.githubusercontent.com/u/54718039?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Onyinye91-ctrl",
    html_url: "https://github.com/Onyinye91-ctrl",
    followers_url: "https://api.github.com/users/Onyinye91-ctrl/followers",
    following_url:
      "https://api.github.com/users/Onyinye91-ctrl/following{/other_user}",
    gists_url: "https://api.github.com/users/Onyinye91-ctrl/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Onyinye91-ctrl/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Onyinye91-ctrl/subscriptions",
    organizations_url: "https://api.github.com/users/Onyinye91-ctrl/orgs",
    repos_url: "https://api.github.com/users/Onyinye91-ctrl/repos",
    events_url: "https://api.github.com/users/Onyinye91-ctrl/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Onyinye91-ctrl/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Jason-Cooke",
    id: 5185660,
    node_id: "MDQ6VXNlcjUxODU2NjA=",
    avatar_url: "https://avatars.githubusercontent.com/u/5185660?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Jason-Cooke",
    html_url: "https://github.com/Jason-Cooke",
    followers_url: "https://api.github.com/users/Jason-Cooke/followers",
    following_url:
      "https://api.github.com/users/Jason-Cooke/following{/other_user}",
    gists_url: "https://api.github.com/users/Jason-Cooke/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Jason-Cooke/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Jason-Cooke/subscriptions",
    organizations_url: "https://api.github.com/users/Jason-Cooke/orgs",
    repos_url: "https://api.github.com/users/Jason-Cooke/repos",
    events_url: "https://api.github.com/users/Jason-Cooke/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Jason-Cooke/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Oner-T",
    id: 23700760,
    node_id: "MDQ6VXNlcjIzNzAwNzYw",
    avatar_url: "https://avatars.githubusercontent.com/u/23700760?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Oner-T",
    html_url: "https://github.com/Oner-T",
    followers_url: "https://api.github.com/users/Oner-T/followers",
    following_url: "https://api.github.com/users/Oner-T/following{/other_user}",
    gists_url: "https://api.github.com/users/Oner-T/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Oner-T/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Oner-T/subscriptions",
    organizations_url: "https://api.github.com/users/Oner-T/orgs",
    repos_url: "https://api.github.com/users/Oner-T/repos",
    events_url: "https://api.github.com/users/Oner-T/events{/privacy}",
    received_events_url: "https://api.github.com/users/Oner-T/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hkjang",
    id: 3069493,
    node_id: "MDQ6VXNlcjMwNjk0OTM=",
    avatar_url: "https://avatars.githubusercontent.com/u/3069493?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hkjang",
    html_url: "https://github.com/hkjang",
    followers_url: "https://api.github.com/users/hkjang/followers",
    following_url: "https://api.github.com/users/hkjang/following{/other_user}",
    gists_url: "https://api.github.com/users/hkjang/gists{/gist_id}",
    starred_url: "https://api.github.com/users/hkjang/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hkjang/subscriptions",
    organizations_url: "https://api.github.com/users/hkjang/orgs",
    repos_url: "https://api.github.com/users/hkjang/repos",
    events_url: "https://api.github.com/users/hkjang/events{/privacy}",
    received_events_url: "https://api.github.com/users/hkjang/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dayon3",
    id: 46526413,
    node_id: "MDQ6VXNlcjQ2NTI2NDEz",
    avatar_url: "https://avatars.githubusercontent.com/u/46526413?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dayon3",
    html_url: "https://github.com/dayon3",
    followers_url: "https://api.github.com/users/dayon3/followers",
    following_url: "https://api.github.com/users/dayon3/following{/other_user}",
    gists_url: "https://api.github.com/users/dayon3/gists{/gist_id}",
    starred_url: "https://api.github.com/users/dayon3/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dayon3/subscriptions",
    organizations_url: "https://api.github.com/users/dayon3/orgs",
    repos_url: "https://api.github.com/users/dayon3/repos",
    events_url: "https://api.github.com/users/dayon3/events{/privacy}",
    received_events_url: "https://api.github.com/users/dayon3/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "thezedwards",
    id: 24527326,
    node_id: "MDQ6VXNlcjI0NTI3MzI2",
    avatar_url: "https://avatars.githubusercontent.com/u/24527326?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/thezedwards",
    html_url: "https://github.com/thezedwards",
    followers_url: "https://api.github.com/users/thezedwards/followers",
    following_url:
      "https://api.github.com/users/thezedwards/following{/other_user}",
    gists_url: "https://api.github.com/users/thezedwards/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/thezedwards/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/thezedwards/subscriptions",
    organizations_url: "https://api.github.com/users/thezedwards/orgs",
    repos_url: "https://api.github.com/users/thezedwards/repos",
    events_url: "https://api.github.com/users/thezedwards/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/thezedwards/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "swdreams",
    id: 1147825,
    node_id: "MDQ6VXNlcjExNDc4MjU=",
    avatar_url: "https://avatars.githubusercontent.com/u/1147825?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/swdreams",
    html_url: "https://github.com/swdreams",
    followers_url: "https://api.github.com/users/swdreams/followers",
    following_url:
      "https://api.github.com/users/swdreams/following{/other_user}",
    gists_url: "https://api.github.com/users/swdreams/gists{/gist_id}",
    starred_url: "https://api.github.com/users/swdreams/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/swdreams/subscriptions",
    organizations_url: "https://api.github.com/users/swdreams/orgs",
    repos_url: "https://api.github.com/users/swdreams/repos",
    events_url: "https://api.github.com/users/swdreams/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/swdreams/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "olufemiolajide",
    id: 9871439,
    node_id: "MDQ6VXNlcjk4NzE0Mzk=",
    avatar_url: "https://avatars.githubusercontent.com/u/9871439?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/olufemiolajide",
    html_url: "https://github.com/olufemiolajide",
    followers_url: "https://api.github.com/users/olufemiolajide/followers",
    following_url:
      "https://api.github.com/users/olufemiolajide/following{/other_user}",
    gists_url: "https://api.github.com/users/olufemiolajide/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/olufemiolajide/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/olufemiolajide/subscriptions",
    organizations_url: "https://api.github.com/users/olufemiolajide/orgs",
    repos_url: "https://api.github.com/users/olufemiolajide/repos",
    events_url: "https://api.github.com/users/olufemiolajide/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/olufemiolajide/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Kipsanga-Gregory",
    id: 47940006,
    node_id: "MDQ6VXNlcjQ3OTQwMDA2",
    avatar_url: "https://avatars.githubusercontent.com/u/47940006?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Kipsanga-Gregory",
    html_url: "https://github.com/Kipsanga-Gregory",
    followers_url: "https://api.github.com/users/Kipsanga-Gregory/followers",
    following_url:
      "https://api.github.com/users/Kipsanga-Gregory/following{/other_user}",
    gists_url: "https://api.github.com/users/Kipsanga-Gregory/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Kipsanga-Gregory/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Kipsanga-Gregory/subscriptions",
    organizations_url: "https://api.github.com/users/Kipsanga-Gregory/orgs",
    repos_url: "https://api.github.com/users/Kipsanga-Gregory/repos",
    events_url:
      "https://api.github.com/users/Kipsanga-Gregory/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Kipsanga-Gregory/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "codingscode",
    id: 50297646,
    node_id: "MDQ6VXNlcjUwMjk3NjQ2",
    avatar_url: "https://avatars.githubusercontent.com/u/50297646?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/codingscode",
    html_url: "https://github.com/codingscode",
    followers_url: "https://api.github.com/users/codingscode/followers",
    following_url:
      "https://api.github.com/users/codingscode/following{/other_user}",
    gists_url: "https://api.github.com/users/codingscode/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/codingscode/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/codingscode/subscriptions",
    organizations_url: "https://api.github.com/users/codingscode/orgs",
    repos_url: "https://api.github.com/users/codingscode/repos",
    events_url: "https://api.github.com/users/codingscode/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/codingscode/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ijagjeet",
    id: 46004289,
    node_id: "MDQ6VXNlcjQ2MDA0Mjg5",
    avatar_url: "https://avatars.githubusercontent.com/u/46004289?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ijagjeet",
    html_url: "https://github.com/ijagjeet",
    followers_url: "https://api.github.com/users/ijagjeet/followers",
    following_url:
      "https://api.github.com/users/ijagjeet/following{/other_user}",
    gists_url: "https://api.github.com/users/ijagjeet/gists{/gist_id}",
    starred_url: "https://api.github.com/users/ijagjeet/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ijagjeet/subscriptions",
    organizations_url: "https://api.github.com/users/ijagjeet/orgs",
    repos_url: "https://api.github.com/users/ijagjeet/repos",
    events_url: "https://api.github.com/users/ijagjeet/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ijagjeet/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "BillionaireMilton",
    id: 52670593,
    node_id: "MDQ6VXNlcjUyNjcwNTkz",
    avatar_url: "https://avatars.githubusercontent.com/u/52670593?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/BillionaireMilton",
    html_url: "https://github.com/BillionaireMilton",
    followers_url: "https://api.github.com/users/BillionaireMilton/followers",
    following_url:
      "https://api.github.com/users/BillionaireMilton/following{/other_user}",
    gists_url: "https://api.github.com/users/BillionaireMilton/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/BillionaireMilton/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/BillionaireMilton/subscriptions",
    organizations_url: "https://api.github.com/users/BillionaireMilton/orgs",
    repos_url: "https://api.github.com/users/BillionaireMilton/repos",
    events_url:
      "https://api.github.com/users/BillionaireMilton/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/BillionaireMilton/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jelsonjay",
    id: 50907905,
    node_id: "MDQ6VXNlcjUwOTA3OTA1",
    avatar_url: "https://avatars.githubusercontent.com/u/50907905?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jelsonjay",
    html_url: "https://github.com/jelsonjay",
    followers_url: "https://api.github.com/users/jelsonjay/followers",
    following_url:
      "https://api.github.com/users/jelsonjay/following{/other_user}",
    gists_url: "https://api.github.com/users/jelsonjay/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jelsonjay/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jelsonjay/subscriptions",
    organizations_url: "https://api.github.com/users/jelsonjay/orgs",
    repos_url: "https://api.github.com/users/jelsonjay/repos",
    events_url: "https://api.github.com/users/jelsonjay/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jelsonjay/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "josemak25",
    id: 33870502,
    node_id: "MDQ6VXNlcjMzODcwNTAy",
    avatar_url: "https://avatars.githubusercontent.com/u/33870502?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/josemak25",
    html_url: "https://github.com/josemak25",
    followers_url: "https://api.github.com/users/josemak25/followers",
    following_url:
      "https://api.github.com/users/josemak25/following{/other_user}",
    gists_url: "https://api.github.com/users/josemak25/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/josemak25/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/josemak25/subscriptions",
    organizations_url: "https://api.github.com/users/josemak25/orgs",
    repos_url: "https://api.github.com/users/josemak25/repos",
    events_url: "https://api.github.com/users/josemak25/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/josemak25/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Omolajacodec",
    id: 39764887,
    node_id: "MDQ6VXNlcjM5NzY0ODg3",
    avatar_url: "https://avatars.githubusercontent.com/u/39764887?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Omolajacodec",
    html_url: "https://github.com/Omolajacodec",
    followers_url: "https://api.github.com/users/Omolajacodec/followers",
    following_url:
      "https://api.github.com/users/Omolajacodec/following{/other_user}",
    gists_url: "https://api.github.com/users/Omolajacodec/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Omolajacodec/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Omolajacodec/subscriptions",
    organizations_url: "https://api.github.com/users/Omolajacodec/orgs",
    repos_url: "https://api.github.com/users/Omolajacodec/repos",
    events_url: "https://api.github.com/users/Omolajacodec/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Omolajacodec/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sammybrave",
    id: 52744168,
    node_id: "MDQ6VXNlcjUyNzQ0MTY4",
    avatar_url: "https://avatars.githubusercontent.com/u/52744168?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sammybrave",
    html_url: "https://github.com/sammybrave",
    followers_url: "https://api.github.com/users/sammybrave/followers",
    following_url:
      "https://api.github.com/users/sammybrave/following{/other_user}",
    gists_url: "https://api.github.com/users/sammybrave/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/sammybrave/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sammybrave/subscriptions",
    organizations_url: "https://api.github.com/users/sammybrave/orgs",
    repos_url: "https://api.github.com/users/sammybrave/repos",
    events_url: "https://api.github.com/users/sammybrave/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sammybrave/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Soldy",
    id: 4786022,
    node_id: "MDQ6VXNlcjQ3ODYwMjI=",
    avatar_url: "https://avatars.githubusercontent.com/u/4786022?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Soldy",
    html_url: "https://github.com/Soldy",
    followers_url: "https://api.github.com/users/Soldy/followers",
    following_url: "https://api.github.com/users/Soldy/following{/other_user}",
    gists_url: "https://api.github.com/users/Soldy/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Soldy/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Soldy/subscriptions",
    organizations_url: "https://api.github.com/users/Soldy/orgs",
    repos_url: "https://api.github.com/users/Soldy/repos",
    events_url: "https://api.github.com/users/Soldy/events{/privacy}",
    received_events_url: "https://api.github.com/users/Soldy/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "onesphereSolution",
    id: 68131887,
    node_id: "MDQ6VXNlcjY4MTMxODg3",
    avatar_url: "https://avatars.githubusercontent.com/u/68131887?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/onesphereSolution",
    html_url: "https://github.com/onesphereSolution",
    followers_url: "https://api.github.com/users/onesphereSolution/followers",
    following_url:
      "https://api.github.com/users/onesphereSolution/following{/other_user}",
    gists_url: "https://api.github.com/users/onesphereSolution/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/onesphereSolution/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/onesphereSolution/subscriptions",
    organizations_url: "https://api.github.com/users/onesphereSolution/orgs",
    repos_url: "https://api.github.com/users/onesphereSolution/repos",
    events_url:
      "https://api.github.com/users/onesphereSolution/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/onesphereSolution/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "cryptoexpertNG",
    id: 36323328,
    node_id: "MDQ6VXNlcjM2MzIzMzI4",
    avatar_url: "https://avatars.githubusercontent.com/u/36323328?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/cryptoexpertNG",
    html_url: "https://github.com/cryptoexpertNG",
    followers_url: "https://api.github.com/users/cryptoexpertNG/followers",
    following_url:
      "https://api.github.com/users/cryptoexpertNG/following{/other_user}",
    gists_url: "https://api.github.com/users/cryptoexpertNG/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/cryptoexpertNG/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/cryptoexpertNG/subscriptions",
    organizations_url: "https://api.github.com/users/cryptoexpertNG/orgs",
    repos_url: "https://api.github.com/users/cryptoexpertNG/repos",
    events_url: "https://api.github.com/users/cryptoexpertNG/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/cryptoexpertNG/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "obascello",
    id: 77841487,
    node_id: "MDQ6VXNlcjc3ODQxNDg3",
    avatar_url: "https://avatars.githubusercontent.com/u/77841487?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/obascello",
    html_url: "https://github.com/obascello",
    followers_url: "https://api.github.com/users/obascello/followers",
    following_url:
      "https://api.github.com/users/obascello/following{/other_user}",
    gists_url: "https://api.github.com/users/obascello/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/obascello/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/obascello/subscriptions",
    organizations_url: "https://api.github.com/users/obascello/orgs",
    repos_url: "https://api.github.com/users/obascello/repos",
    events_url: "https://api.github.com/users/obascello/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/obascello/received_events",
    type: "User",
    site_admin: false,
  },
];
